### ISSUE TITLE
Finding game through matchmaking requires too much effort

### ISSUE THREAD

**Issue by stashymane** [sammybun/sammyhud#1]
The find game button is at the top of the screen, which redirects you to a prompt at the very bottom of the screen, which then brings a menu on the right. Too much mouse movement - the gamemode menu can be moved to the top to minimize movement required.

**Comment by stashymane** [comment]
And in general there is an issue where the menus that you actually need are placed on different edges of the screen and you need to move your mouse across it several times to accomplish a simple task

**Comment by sammybun** [comment]
This is an issue with the base TF2 hud having a shade placed on it that does not cover the entire screen. Having the matchmaking options at the bottom covers up the large rectangle at the bottom of the screen.
